version: "3.1"

services:
  postgres:
    image: postgres
    volumes:
      - ./postgresdb/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # env_file: .env
    environment:
      POSTGRES_DB: 'todo'
      POSTGRES_USER: 'murad'
      POSTGRES_PASSWORD: '12345'
      # POSTGRES_HOST: 'postgres'

  web:
    build: .
    restart: "always"
    ports:
      - "8000:8000"
    volumes:
      - .:/code/
    depends_on:
      - "postgres"


  # redis_container:
  #   image: redis
  #   restart: "always"
  #   ports: 
  #     - 6379:6379
